using Microsoft.AspNetCore.Http;
using Project.Core.Enum;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Project.Models.GeneralModel
{
    /// <summary>
    /// Single source of truth for the non-diagnostic disclaimer (Doc 2: this is not a
    /// medical device). Kept as a constant so no response can be produced without it,
    /// even if configuration is missing.
    /// </summary>
    public static class IllHealthConstants
    {
        public const string Disclaimer =
            "This result is generated by an automated tool for informational purposes only. " +
            "It is NOT a veterinary diagnosis and this app is not a medical device. " +
            "Always consult a qualified veterinarian for advice about your pet's health.";

        // Below this max-confidence value the AI result is treated as inconclusive.
        public const decimal LowConfidenceThreshold = 0.50m;
    }

    /// <summary>
    /// Service-layer input for an ill-health analysis. Populated by the controller from
    /// the multipart request (matches the existing IFormFile upload pattern).
    /// </summary>
    public class IllHealthAnalyzeRequest
    {
        public string PetId { get; set; }
        public IFormFile Image { get; set; }
        public EnumHealthCheckSpecies Species { get; set; }
        // The authenticated user id (audit + ownership check). Set by the controller.
        public System.Guid CurrentUserId { get; set; }
    }

    /// <summary>
    /// Raw output shape expected back from the Python AI service
    /// (POST {IllHealthAiUrl}ai/illhealth/analyze). Deserialized case-insensitively.
    /// </summary>
    public class IllHealthAiResult
    {
        [JsonPropertyName("conditions")]
        public List<IllHealthAiCondition> Conditions { get; set; } = new List<IllHealthAiCondition>();

        [JsonPropertyName("summary")]
        public string Summary { get; set; }

        [JsonPropertyName("model_version")]
        public string ModelVersion { get; set; }

        // AI signals it could not read the image clearly.
        [JsonPropertyName("image_unclear")]
        public bool ImageUnclear { get; set; }
    }

    public class IllHealthAiCondition
    {
        [JsonPropertyName("condition_name")]
        public string ConditionName { get; set; }

        [JsonPropertyName("affected_area")]
        public string AffectedArea { get; set; }

        // 0..1
        [JsonPropertyName("confidence")]
        public decimal Confidence { get; set; }

        // 1 (low) .. 3 (high)
        [JsonPropertyName("severity")]
        public int Severity { get; set; }
    }

    /// <summary>
    /// Structured response returned to mobile. The <see cref="Disclaimer"/> property is
    /// initialized to the constant so it is present on EVERY response by construction.
    /// </summary>
    public class IllHealthResponse
    {
        [JsonPropertyName("event_id")]
        public string EventId { get; set; }

        [JsonPropertyName("conditions")]
        public List<IllHealthConditionDto> Conditions { get; set; } = new List<IllHealthConditionDto>();

        [JsonPropertyName("guidance_text")]
        public string GuidanceText { get; set; }

        [JsonPropertyName("severity_level")]
        public string SeverityLevel { get; set; }

        [JsonPropertyName("recommended_action")]
        public string RecommendedAction { get; set; }

        [JsonPropertyName("disclaimer")]
        public string Disclaimer { get; set; } = IllHealthConstants.Disclaimer;

        [JsonPropertyName("is_stub")]
        public bool IsStub { get; set; } = true;
    }

    public class IllHealthConditionDto
    {
        [JsonPropertyName("condition_name")]
        public string ConditionName { get; set; }

        [JsonPropertyName("affected_area")]
        public string AffectedArea { get; set; }

        [JsonPropertyName("confidence")]
        public decimal Confidence { get; set; }

        [JsonPropertyName("severity")]
        public int Severity { get; set; }
    }
}
