//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Project.Services.Resources.Messages_Resources", typeof(Messages_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} added you in expense. Click link to settle this {1}.
        /// </summary>
        internal static string AddedToGroup_ANONYMOUS {
            get {
                return ResourceManager.GetString("AddedToGroup_ANONYMOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exists..
        /// </summary>
        internal static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Exists..
        /// </summary>
        internal static string AlreadyExists1 {
            get {
                return ResourceManager.GetString("AlreadyExists1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank not found..
        /// </summary>
        internal static string BankNotFound {
            get {
                return ResourceManager.GetString("BankNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your branch is deactivated..
        /// </summary>
        internal static string BranchDeactivated {
            get {
                return ResourceManager.GetString("BranchDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch with same name already exists for this business..
        /// </summary>
        internal static string BranchExists {
            get {
                return ResourceManager.GetString("BranchExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch not exists..
        /// </summary>
        internal static string BranchNotExists {
            get {
                return ResourceManager.GetString("BranchNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch added successfully.
        /// </summary>
        internal static string BranchSuccess {
            get {
                return ResourceManager.GetString("BranchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch updated successfully..
        /// </summary>
        internal static string BranchUpdateSuccess {
            get {
                return ResourceManager.GetString("BranchUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your business is deactivated..
        /// </summary>
        internal static string BusinessDeactivated {
            get {
                return ResourceManager.GetString("BusinessDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business details not found..
        /// </summary>
        internal static string BusinessDetailsNotFound {
            get {
                return ResourceManager.GetString("BusinessDetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business with same name already exists..
        /// </summary>
        internal static string BusinessNameAlreadyExists {
            get {
                return ResourceManager.GetString("BusinessNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This company number already exists..
        /// </summary>
        internal static string BusinessNumberAlreadyExists {
            get {
                return ResourceManager.GetString("BusinessNumberAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password at the moment, Please try again after sometime..
        /// </summary>
        internal static string ChangePasswordFailure {
            get {
                return ResourceManager.GetString("ChangePasswordFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password at the moment, Please try again after sometime..
        /// </summary>
        internal static string ChangePasswordFailure1 {
            get {
                return ResourceManager.GetString("ChangePasswordFailure1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered email is a {0}. Please try to reset password with {1} app..
        /// </summary>
        internal static string ChangePasswordWithCorrectApp {
            get {
                return ResourceManager.GetString("ChangePasswordWithCorrectApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation link Send Successfully.
        /// </summary>
        internal static string ConfirmEmailLink {
            get {
                return ResourceManager.GetString("ConfirmEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Confirmation link Send Successfully.
        /// </summary>
        internal static string ConfirmEmailLink1 {
            get {
                return ResourceManager.GetString("ConfirmEmailLink1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Created Successfully !.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Created Successfully !.
        /// </summary>
        internal static string Create1 {
            get {
                return ResourceManager.GetString("Create1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted Successfully !.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Deleted Successfully !.
        /// </summary>
        internal static string Delete1 {
            get {
                return ResourceManager.GetString("Delete1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload your document at the moment, Please try again later..
        /// </summary>
        internal static string DocumentUpdateError {
            get {
                return ResourceManager.GetString("DocumentUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has requested {1} from you. Click the link to continue: {2}.
        /// </summary>
        internal static string EcommercePaymentRequest {
            get {
                return ResourceManager.GetString("EcommercePaymentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id is already exists..
        /// </summary>
        internal static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered with us..
        /// </summary>
        internal static string EmailAlreadyRegisteredWithUs {
            get {
                return ResourceManager.GetString("EmailAlreadyRegisteredWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is not registered with SSV SmartPay..
        /// </summary>
        internal static string EmailNotRegisteredWithUs {
            get {
                return ResourceManager.GetString("EmailNotRegisteredWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Address is not valid..
        /// </summary>
        internal static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verified Successfully!.
        /// </summary>
        internal static string EmailVerified {
            get {
                return ResourceManager.GetString("EmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Verified Successfully!.
        /// </summary>
        internal static string EmailVerified1 {
            get {
                return ResourceManager.GetString("EmailVerified1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred !.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Error Occurred !.
        /// </summary>
        internal static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Expired!.
        /// </summary>
        internal static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Expired!.
        /// </summary>
        internal static string Expired1 {
            get {
                return ResourceManager.GetString("Expired1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed..
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed..
        /// </summary>
        internal static string Fail1 {
            get {
                return ResourceManager.GetString("Fail1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not found..
        /// </summary>
        internal static string GroupNotFound {
            get {
                return ResourceManager.GetString("GroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data InActive!.
        /// </summary>
        internal static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data InActive!.
        /// </summary>
        internal static string InActive1 {
            get {
                return ResourceManager.GetString("InActive1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password in invalid..
        /// </summary>
        internal static string InvalidCurrentPassword {
            get {
                return ResourceManager.GetString("InvalidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is invalid..
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is invalid..
        /// </summary>
        internal static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username or Password..
        /// </summary>
        internal static string InvalidUsernamePassword {
            get {
                return ResourceManager.GetString("InvalidUsernamePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contact matched..
        /// </summary>
        internal static string NoContactMatched {
            get {
                return ResourceManager.GetString("NoContactMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Active Subscription.
        /// </summary>
        internal static string NotActiveSubscription {
            get {
                return ResourceManager.GetString("NotActiveSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exists!.
        /// </summary>
        internal static string NotExists {
            get {
                return ResourceManager.GetString("NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Exists!.
        /// </summary>
        internal static string NotExists1 {
            get {
                return ResourceManager.GetString("NotExists1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can not be same as current password..
        /// </summary>
        internal static string OldNewPasswordMatch {
            get {
                return ResourceManager.GetString("OldNewPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#&gt;Your Verification Service verification code is: {0}
        ///{1}.
        /// </summary>
        internal static string OTP_SMS {
            get {
                return ResourceManager.GetString("OTP_SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully.
        /// </summary>
        internal static string PasswordChangeSuccess {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed successfully.
        /// </summary>
        internal static string PasswordChangeSuccess1 {
            get {
                return ResourceManager.GetString("PasswordChangeSuccess1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update password..
        /// </summary>
        internal static string PasswordUpdatedError {
            get {
                return ResourceManager.GetString("PasswordUpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password updated successfully..
        /// </summary>
        internal static string PasswordUpdatedSuccess {
            get {
                return ResourceManager.GetString("PasswordUpdatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number already exists..
        /// </summary>
        internal static string PhoneAlreadyExists {
            get {
                return ResourceManager.GetString("PhoneAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile not found..
        /// </summary>
        internal static string ProfileNotFound {
            get {
                return ResourceManager.GetString("ProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link has been sent on your registered email id.
        /// </summary>
        internal static string ResetPasswordSubmitted {
            get {
                return ResourceManager.GetString("ResetPasswordSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password reset link has been sent on your registered email id.
        /// </summary>
        internal static string ResetPasswordSubmitted1 {
            get {
                return ResourceManager.GetString("ResetPasswordSubmitted1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set selected bank account as primary account..
        /// </summary>
        internal static string SetPrimaryError {
            get {
                return ResourceManager.GetString("SetPrimaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account set as primary account..
        /// </summary>
        internal static string SetPrimarySuccess {
            get {
                return ResourceManager.GetString("SetPrimarySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Added Successfully..
        /// </summary>
        internal static string StaffAddedSuccessfully {
            get {
                return ResourceManager.GetString("StaffAddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Successful..
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Successful..
        /// </summary>
        internal static string Success1 {
            get {
                return ResourceManager.GetString("Success1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is {0}. Please try to login with {1} app..
        /// </summary>
        internal static string TryToLoginWithDynamicApp {
            get {
                return ResourceManager.GetString("TryToLoginWithDynamicApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is {0}. Please try to login with Merchant app..
        /// </summary>
        internal static string TryToLoginWithMerchantApp {
            get {
                return ResourceManager.GetString("TryToLoginWithMerchantApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Update Successfully !.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Update Successfully !.
        /// </summary>
        internal static string Update1 {
            get {
                return ResourceManager.GetString("Update1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username already exists..
        /// </summary>
        internal static string UsernameAlreadyExists {
            get {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not belongs to selected branch..
        /// </summary>
        internal static string UserNotBelongsToBranch {
            get {
                return ResourceManager.GetString("UserNotBelongsToBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Address is not valid.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Email Address is not valid.
        /// </summary>
        internal static string UserNotFound1 {
            get {
                return ResourceManager.GetString("UserNotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Successfully !.
        /// </summary>
        internal static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Successfully !.
        /// </summary>
        internal static string Verified1 {
            get {
                return ResourceManager.GetString("Verified1", resourceCulture);
            }
        }
    }
}
